package cmd.entidade;
// Generated 23/05/2017 06:48:11 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

    private Integer codMaterial;//BD

    //private Construcao construcao;
    private String descricao;
    private String nomeUnidade;
    private BigDecimal constanteMetro;
    private BigDecimal precoUnitario;
    private Boolean ehOpcional;
    //private Integer qualidade;//Não tem no Diagrama de classe
    private String tipo;
    private Integer quantidadeMinima;

     //private Set materialItems = new HashSet(0);//???????
    private Boolean xdead;//BD

    public Material() {
    }

    //public Material(Construcao construcao, String descricao, String nomeUnidade, BigDecimal constanteMetro, BigDecimal precoUnitario, Boolean ehOpcional, Integer qualidade, String tipo, Integer quantidadeMinima, Boolean xdead, Set materialItems) {
    public Material(String descricao, String nomeUnidade, BigDecimal constanteMetro, BigDecimal precoUnitario, Boolean ehOpcional, String tipo, Integer quantidadeMinima, Boolean xdead) {
        //this.construcao = construcao;
        this.descricao = descricao;
        this.nomeUnidade = nomeUnidade;
        this.constanteMetro = constanteMetro;
        this.precoUnitario = precoUnitario;
        this.ehOpcional = ehOpcional;
        //this.qualidade = qualidade;
        this.tipo = tipo;
        this.quantidadeMinima = quantidadeMinima;
        this.xdead = xdead;
        //this.materialItems = materialItems;
    }

    public Integer getCodMaterial() {
        return this.codMaterial;
    }

    public void setCodMaterial(Integer codMaterial) {
        this.codMaterial = codMaterial;
    }
//    public Construcao getConstrucao() {
//        return this.construcao;
//    }
//    
//    public void setConstrucao(Construcao construcao) {
//        this.construcao = construcao;
//    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getNomeUnidade() {
        return this.nomeUnidade;
    }

    public void setNomeUnidade(String nomeUnidade) {
        this.nomeUnidade = nomeUnidade;
    }

    public BigDecimal getConstanteMetro() {
        return this.constanteMetro;
    }

    public void setConstanteMetro(BigDecimal constanteMetro) {
        this.constanteMetro = constanteMetro;
    }

    public BigDecimal getPrecoUnitario() {
        return this.precoUnitario;
    }

    public void setPrecoUnitario(BigDecimal precoUnitario) {
        this.precoUnitario = precoUnitario;
    }

    public Boolean getEhOpcional() {
        return this.ehOpcional;
    }

    public void setEhOpcional(Boolean ehOpcional) {
        this.ehOpcional = ehOpcional;
    }
//    public Integer getQualidade() {
//        return this.qualidade;
//    }
//    
//    public void setQualidade(Integer qualidade) {
//        this.qualidade = qualidade;
//    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Integer getQuantidadeMinima() {
        return this.quantidadeMinima;
    }

    public void setQuantidadeMinima(Integer quantidadeMinima) {
        this.quantidadeMinima = quantidadeMinima;
    }

    public Boolean getXdead() {
        return this.xdead;
    }

    public void setXdead(Boolean xdead) {
        this.xdead = xdead;
    }
//    public Set getMaterialItems() {
//        return this.materialItems;
//    }
//    
//    public void setMaterialItems(Set materialItems) {
//        this.materialItems = materialItems;
//    }

}
