package cmd.entidade;
// Generated 23/05/2017 06:48:11 by Hibernate Tools 4.3.1

/**
 * Telefone generated by hbm2java
 */
public class Telefone implements java.io.Serializable {

    private TelefoneId id;//BD
    //private Cliente cliente;
    private Boolean xdead;//BD

    public Telefone() {
    }

    //public Telefone(TelefoneId id, Cliente cliente) {
    public Telefone(TelefoneId id) {
        this.id = id;
        //this.cliente = cliente;
    }

    //public Telefone(TelefoneId id, Cliente cliente, Boolean xdead) {

    public Telefone(TelefoneId id, Boolean xdead) {
        this.id = id;
        //this.cliente = cliente;
        this.xdead = xdead;
    }

    public TelefoneId getId() {
        return this.id;
    }

    public void setId(TelefoneId id) {
        this.id = id;
    }
//    public Cliente getCliente() {
//        return this.cliente;
//    }
//    
//    public void setCliente(Cliente cliente) {
//        this.cliente = cliente;
//    }

    public Boolean getXdead() {
        return this.xdead;
    }

    public void setXdead(Boolean xdead) {
        this.xdead = xdead;
    }

}
